import test from 'node:test';
import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
import { liveHarness } from './live-harness.mjs';
import { consoleProcess } from '../test/console-harness.mjs';
import { connect } from '../test/harness.mjs';

test('Actual Herdr Ctrl+c interrupts a disposable sleep; receipt and manual recovery remain independent', async t => {
  const h = await liveHarness(t);
  const console = await consoleProcess(t, h, { observationMs: 1500 }), client = await connect(console.ready.socket, t);
  const target = (await client.call('pane_describe', { pane_id: h.pane.pane_id })).target;
  const scope = { profile: 'local_posix', cwd: h.root, paths: [h.root], trusted: true };
  const initial = await client.call('job_start', { pane_id: target.pane_id, objective: 'interrupt owned sleep', action_scope: scope });
  const job = await client.call('job_wait', { job_id: initial.job_id, wait_ms: 1000 });
  const common = { job_id: job.job_id, target, objective: 'interrupt owned sleep', cwd: h.root, env: {}, affected_paths: [h.root], risk: { classification: 'bounded_change', inspected: true, impact: 'Start/stop only the disposable test sleep', recovery: 'No persistent data to recover', uncertainties: [], categories: [] } };
  const original = await client.call('action_propose', { ...common, operation: 'execute', command: 'exec sleep 20' });
  assert.equal((await client.call('action_submit', { proposal_id: original.proposal_id })).submission_state, 'accepted');
  await new Promise(resolve => setTimeout(resolve, 250));
  const busy = await console.command(`inspect ${target.pane_id}`);
  assert.equal(busy.shell_ready, false, JSON.stringify(busy));
  const proposed = await client.call('action_propose', { ...common, operation: 'interrupt', original_proposal_id: original.proposal_id });
  assert.deepEqual(proposed.payload, { text: '', keys: ['Ctrl+c'] });
  const receipt = await client.call('action_submit', { proposal_id: proposed.proposal_id });
  assert.equal(receipt.submission_state, 'accepted');
  assert.equal(receipt.observation_state, 'not_applicable');
  await new Promise(resolve => setTimeout(resolve, 1600));
  const outcome = await client.call('action_status', { job_id: job.job_id, proposal_id: original.proposal_id });
  assert.equal(outcome.observation_state, 'outcome_unknown');
  assert.equal(outcome.exit_code, null);
  const ready = await console.command(`inspect ${target.pane_id}`);
  assert.equal(ready.shell_ready, true);
  assert.equal(ready.held_proposal_id, original.proposal_id);
  const recovered = await console.command(`recover ${original.proposal_id} verify fresh shell`);
  assert.equal(recovered.recovery, 'user_verified_ready_shell');
  assert.equal(recovered.exit_code, null);
  assert.equal((await console.command('status')).held_terminal_count, 0);
  const follow = await client.call('job_start', { pane_id: target.pane_id, objective: 'verify fresh shell', action_scope: scope });
  await client.call('job_wait', { job_id: follow.job_id, wait_ms: 1000 });
  const check = await client.call('action_propose', { ...common, job_id: follow.job_id, objective: 'verify fresh shell', operation: 'execute', command: 'printf "fresh shell checked\\n"' });
  assert.equal((await client.call('action_submit', { proposal_id: check.proposal_id })).submission_state, 'accepted');
  await new Promise(resolve => setTimeout(resolve, 300));
  const final = await client.call('action_status', { job_id: follow.job_id, proposal_id: check.proposal_id });
  assert.equal(final.exit_code, 0);
  const wires = h.calls.filter(call => call.method === 'pane.send_input');
  assert.equal(wires.length, 3);
  const record = { at: new Date().toISOString(), node: process.versions.node, herdr: '0.9.0', protocol: 22, target, boundary: 'actual disposable Herdr POSIX shell, actual interactive Broker console, public MCP; observing proxy', busy, interrupt: receipt, original: outcome, ready, recovered, final, wire_attempts: wires.length, automatic_ctrl_c: 0 };
  await writeFile(new URL('../docs/implementation/issue-20-local-acceptance.json', import.meta.url), JSON.stringify(record, null, 2).replaceAll(h.root, '<disposable-cwd>') + '\n');
});
